# 5 pandas入门
pandas是本书后续内容的⾸选库。它含有使数据清洗和分析
⼯作变得更快更简单的数据结构和操作⼯具。pandas经常和
其它⼯具⼀同使⽤，如数值计算⼯具NumPy和SciPy，分析库
statsmodels和scikit-learn，和数据可视化库matplotlib。
pandas是基于NumPy数组构建的，特别是基于数组的函数和
不使⽤for循环的数据处理。
虽然pandas采⽤了⼤量的NumPy编码⻛格，但⼆者最⼤的不
同是pandas是专门为处理表格和混杂数据设计的。⽽NumPy
更适合处理统⼀的数值数组数据。

## 5.1 pandas的数据结构介绍

In [7]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [2]:
obj = pd.Series([-1,2,3,0])
obj

0   -1
1    2
2    3
3    0
dtype: int64

In [3]:
obj.values, obj.index

(array([-1,  2,  3,  0]), RangeIndex(start=0, stop=4, step=1))

In [4]:
obj2 = pd.Series([1, 2,3,4], index=['a','b', 'c', 'd'])
obj2

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
obj2['a']

np.int64(1)

In [6]:
obj2[obj2>2]

c    3
d    4
dtype: int64

In [8]:
np.exp(obj2)

a     2.718282
b     7.389056
c    20.085537
d    54.598150
dtype: float64

In [10]:
# 如果数据被存放在⼀个Python字典中，也可以直接通过这个字典来创建Series
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
# 如果只传⼊⼀个字典，则结果Series中的索引就是原字典的键（有序排列）。你可以传⼊排好序的字典的键以改变顺序：
# 在这个例⼦中，sdata中跟states索引相匹配的那3个值会被找出来并放到相应的位置上，但由于"California"所对应的sdata值找不到，所以其结果就为NaN（即“⾮数字”（not a
# number），在pandas中，它⽤于表⽰缺失或NA值）。因为‘Utah’不在states中，它被从结果中除去。
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [12]:
# 我将使⽤缺失（missing）或NA表⽰缺失数据。pandas的isnull和notnull函数可⽤于检测缺失数据：
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [13]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [15]:
# Series也有类似的实例⽅法：
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [16]:
# 对于许多应⽤⽽⾔，Series最重要的⼀个功能是，它会根据运算的索引标签⾃动对⻬数据：
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [17]:
# Series对象本⾝及其索引都有⼀个name属性，该属性跟pandas其他的关键功能关系⾮常密切：
obj4.name = 'population'
obj4.index.name = 'state'  
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [18]:
# Series的索引可以通过赋值的⽅式就地修改：
obj

0   -1
1    2
2    3
3    0
dtype: int64

In [19]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob     -1
Steve    2
Jeff     3
Ryan     0
dtype: int64

## DataFrame
DataFrame是⼀个表格型的数据结构，它含有⼀组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）。
DataFrame既有⾏索引也有列索引，它可以被看做由Series组成的字典（共⽤同⼀个索引）。DataFrame中的数据是以⼀个或多个⼆维块存放的（⽽不是列表、字典或别的⼀维数据结构）。
虽然DataFrame是以⼆维结构保存数据的，但你仍然可以轻松地将其表⽰为更⾼维度的数据（层次化索引的表格型结构
建DataFrame的办法有很多，最常⽤的⼀种是直接传⼊⼀个由等⻓列表或NumPy数组组成的字典：

In [22]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year':[2000, 2001, 2002, 2001, 2002],
        'pop':[1.5, 1.7, 3.6, 2.4, 2.9]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [24]:
# 对于特别⼤的DataFrame，head⽅法会选取前五⾏：
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [28]:
# 如果指定了列序列，则DataFrame的列就会按照指定顺序进⾏排列：
pd.DataFrame(data, columns=['year', 'pop', 'state'])

   year  pop   state
0  2000  1.5    Ohio
1  2001  1.7    Ohio
2  2002  3.6    Ohio
3  2001  2.4  Nevada
4  2002  2.9  Nevada

In [37]:
# 如果传⼊的列在DataFrame中找不到，就会在结果中添加⼀列，值全部设为NaN：
frame2 = pd.DataFrame(data, columns=['state', 'pop', 'year', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five'])
frame2

        state  pop  year debt
one      Ohio  1.5  2000  NaN
two      Ohio  1.7  2001  NaN
three    Ohio  3.6  2002  NaN
four   Nevada  2.4  2001  NaN
five   Nevada  2.9  2002  NaN

In [38]:
frame2.columns = ['year', 'state', 'pop', 'debt']
frame2

         year  state   pop debt
one      Ohio    1.5  2000  NaN
two      Ohio    1.7  2001  NaN
three    Ohio    3.6  2002  NaN
four   Nevada    2.4  2001  NaN
five   Nevada    2.9  2002  NaN

In [40]:
# 通过类似字典标记的⽅式或属性的⽅式，可以将DataFrame的列获取为⼀个Series：
frame2['state'], frame2.columns

(one      1.5
 two      1.7
 three    3.6
 four     2.4
 five     2.9
 Name: state, dtype: float64,
 Index(['year', 'state', 'pop', 'debt'], dtype='object'))

In [41]:
# ⾏也可以通过位置或名称的⽅式进⾏获取，⽐如⽤loc属性
frame2.loc['three']

year     Ohio
state     3.6
pop      2002
debt      NaN
Name: three, dtype: object